""""add last-monitored to teams"

Revision ID: 58e83a81dcd1
Revises: 1252433279ce
Create Date: 2025-06-25 07:18:09.620033+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e83a81dcd1'
down_revision: Union[str, None] = '1252433279ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('last_monitored', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'last_monitored')
    # ### end Alembic commands ###