"""add litellm api url to private ai keys

Revision ID: 00c5de5fd13f
Revises: 
Create Date: 2025-02-18 04:26:27.655267+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c5de5fd13f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_tokens', sa.Column('litellm_api_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_tokens', 'litellm_api_url')
    # ### end Alembic commands ###