"""pricing-tables

Revision ID: 5bda44ccd008
Revises: cba2089aadd8
Create Date: 2025-08-25 09:32:08.702928+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bda44ccd008'
down_revision: Union[str, None] = 'cba2089aadd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_type', sa.String(), nullable=False),
    sa.Column('pricing_table_id', sa.String(), nullable=False),
    sa.Column('stripe_publishable_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_type', 'is_active', name='uq_pricing_table_type_active')
    )
    op.create_index(op.f('ix_pricing_tables_id'), 'pricing_tables', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_tables_table_type'), 'pricing_tables', ['table_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_tables_table_type'), table_name='pricing_tables')
    op.drop_index(op.f('ix_pricing_tables_id'), table_name='pricing_tables')
    op.drop_table('pricing_tables')
    # ### end Alembic commands ###