""""add always free to teams"

Revision ID: 1252433279ce
Revises: c2f3f1999f62
Create Date: 2025-06-13 07:59:59.128601+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1252433279ce'
down_revision: Union[str, None] = 'c2f3f1999f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('is_always_free', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'is_always_free')
    # ### end Alembic commands ###