"""Add system settings

Revision ID: 891e02a9ce6e
Revises: 2bb3f48b650d
Create Date: 2025-05-16 09:07:27.786841+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '891e02a9ce6e'
down_revision: Union[str, None] = '2bb3f48b650d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_secrets_id'), 'system_secrets', ['id'], unique=False)
    op.create_index(op.f('ix_system_secrets_key'), 'system_secrets', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_secrets_key'), table_name='system_secrets')
    op.drop_index(op.f('ix_system_secrets_id'), table_name='system_secrets')
    op.drop_table('system_secrets')
    # ### end Alembic commands ###