"""team product relationship

Revision ID: c2f3f1999f62
Revises: 1069b3617025
Create Date: 2025-05-20 11:27:22.451900+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2f3f1999f62'
down_revision: Union[str, None] = '1069b3617025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('keys_per_user', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('total_key_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('service_key_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('max_budget_per_key', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('rpm_per_key', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('vector_db_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('vector_db_storage', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('renewal_period_days', sa.Integer(), nullable=True))
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_products_stripe_lookup_key', table_name='products')
    op.drop_column('products', 'stripe_lookup_key')

    op.create_table('team_products',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'product_id')
    )
    op.add_column('teams', sa.Column('last_payment', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_teams_stripe_customer_id'), 'teams', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_stripe_customer_id'), table_name='teams')
    op.drop_column('teams', 'last_payment')
    op.add_column('products', sa.Column('stripe_lookup_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_products_stripe_lookup_key', 'products', ['stripe_lookup_key'], unique=True)
    op.drop_table('team_products')
    op.alter_column('products', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('products', 'renewal_period_days')
    op.drop_column('products', 'vector_db_storage')
    op.drop_column('products', 'vector_db_count')
    op.drop_column('products', 'rpm_per_key')
    op.drop_column('products', 'max_budget_per_key')
    op.drop_column('products', 'service_key_count')
    op.drop_column('products', 'total_key_count')
    op.drop_column('products', 'keys_per_user')
    op.drop_column('products', 'user_count')
    # ### end Alembic commands ###