""""Retention periods"

Revision ID: ffe12e7d7040
Revises: 8901ce90a061
Create Date: 2025-10-24 12:05:35.947144+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe12e7d7040'
down_revision: Union[str, None] = '8901ce90a061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('teams', sa.Column('retention_warning_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'retention_warning_sent_at')
    op.drop_column('teams', 'deleted_at')
    # ### end Alembic commands ###