"""add team metrics table

Revision ID: add_team_metrics_table
Revises: 5bda44ccd008
Create Date: 2025-01-27 12:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_team_metrics_table'
down_revision: Union[str, None] = '5bda44ccd008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Float(), nullable=False),
    sa.Column('last_spend_calculation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regions', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index(op.f('ix_team_metrics_id'), 'team_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_team_metrics_team_id'), 'team_metrics', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_metrics_team_id'), table_name='team_metrics')
    op.drop_index(op.f('ix_team_metrics_id'), table_name='team_metrics')
    op.drop_table('team_metrics')
    # ### end Alembic commands ###

