"""add_force_user_keys_to_teams

Revision ID: 0ba9c30d601d
Revises: ffe12e7d7040
Create Date: 2026-01-20 21:25:35.815848+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba9c30d601d'
down_revision: Union[str, None] = 'ffe12e7d7040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('force_user_keys', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'force_user_keys')
    # ### end Alembic commands ###