"""add label to regions

Revision ID: 646f3aa3b394
Revises: 0ba9c30d601d
Create Date: 2026-01-30 20:28:35.668898+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646f3aa3b394'
down_revision: Union[str, None] = '0ba9c30d601d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'label')
    # ### end Alembic commands ###