site_name: amazee.ai Documentation
site_description: Complete documentation for amazee.ai - Private AI Keys as a Service
site_author: amazee.io
site_url: https://docs.amazee.ai

# Repository
repo_name: amazeeio/amazee.ai
repo_url: https://github.com/amazeeio/amazee.ai
edit_uri: edit/main/docs/web/

# Copyright
copyright: Copyright &copy; 2025 amazee.io

# Theme configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.result
    - navigation.instant.suggest
    - navigation.instant.tracking
    - navigation.instant.worker
    - navigation.instant.worker.offline
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.tracking.instant
    - navigation.tracking.instant.worker
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  logo: assets/logo.svg
  favicon: assets/favicon.png

# Navigation structure
nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - User Guide: user-guide.md
  - API Reference: api-reference.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra configuration
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amazeeio/amazee.ai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/amazeeio
    - icon: fontawesome/brands/discord
      link: https://discord.gg/amazee
  generator: false

# Validation
validation:
  nav:
    omitted_files: ignore
  not_found: warn

# Build configuration
docs_dir: docs/web
site_dir: site

# Dev server configuration
dev_addr: 127.0.0.1:8000