ingest:
  kafka:
    broker: kafka:9092
    brokerAddressFamily: v4
    socketKeepAliveEnable: true
    topicMetadataRefreshInterval: 10s

aggregation:
  clickhouse:
    address: clickhouse:9000
    auth:
      username: default
      password: default
      database: openmeter

sink:
  minCommitCount: 1
  namespaceRefetch: 1s
  namespaceRefetchTimeout: 1s
  kafka:
    brokers: kafka:9092
    brokerAddressFamily: v4
    socketKeepAliveEnable: true
    topicMetadataRefreshInterval: 10s
  dedupe:
    enabled: false

postgres:
  url: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
  autoMigrate: migration # Runs migrations as part of the service startup, valid values are: ent, migration, false

meters:
  - id: completion_tokens_1
    slug: completion_tokens_1
    description: "Track completion tokens from litellm requests"
    eventType: litellm_tokens
    valueProperty: $.data.completion_tokens
    aggregation: SUM
    groupBy:
      subject: $.subject
      model: $.data.model
      source: $.source

  - id: prompt_tokens_1
    slug: prompt_tokens_1
    description: "Track prompt tokens from litellm requests"
    eventType: litellm_tokens
    valueProperty: $.data.prompt_tokens
    aggregation: SUM
    groupBy:
      subject: $.subject
      model: $.data.model
      source: $.source

  - id: total_tokens_1
    slug: total_tokens_1
    description: "Track total tokens from litellm requests"
    eventType: litellm_tokens
    valueProperty: $.data.total_tokens
    aggregation: SUM
    groupBy:
      subject: $.subject
      model: $.data.model
      source: $.source

portal:
  enabled: true
  tokenSecret: this-isnt-secure