ingest:
  kafka:
    broker: kafka:9092
    brokerAddressFamily: v4
    socketKeepAliveEnable: true
    topicMetadataRefreshInterval: 10s

aggregation:
  clickhouse:
    address: clickhouse:9000
    auth:
      username: default
      password: default
      database: openmeter

sink:
  minCommitCount: 1
  namespaceRefetch: 1s
  namespaceRefetchTimeout: 1s
  kafka:
    brokers: kafka:9092
    brokerAddressFamily: v4
    socketKeepAliveEnable: true
    topicMetadataRefreshInterval: 10s
  dedupe:
    enabled: true
    driver: redis
    config:
      address: redis:6379
      database: 0
      expiration: 768h # 32d

postgres:
  url: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
  autoMigrate: migration # Runs migrations as part of the service startup, valid values are: ent, migration, false

meters:
  - id: completion_tokens_4
    slug: completion_tokens_4
    name: "Completion Tokens"
    description: "Track completion tokens from litellm requests"
    eventType: litellm_tokens
    valueProperty: $.completion_tokens
    aggregation: SUM
    groupBy:
      model: $.model

  - id: prompt_tokens_3
    slug: prompt_tokens_3
    name: "Prompt Tokens"
    description: "Track prompt tokens from litellm requests"
    eventType: litellm_tokens
    valueProperty: $.prompt_tokens
    aggregation: SUM
    groupBy:
      model: $.model

  - id: total_tokens_3
    slug: total_tokens_3
    name: "Total Tokens"
    description: "Track total tokens from litellm requests"
    eventType: litellm_tokens
    valueProperty: $.total_tokens
    aggregation: SUM
    groupBy:
      model: $.model

portal:
  enabled: true
  tokenSecret: this-isnt-secure