ingest:
  kafka:
    broker: kafka:9092
    brokerAddressFamily: v4
    socketKeepAliveEnable: true
    topicMetadataRefreshInterval: 10s

aggregation:
  clickhouse:
    address: clickhouse:9000
    auth:
      username: default
      password: default
      database: openmeter

sink:
  minCommitCount: 1
  namespaceRefetch: 1s
  namespaceRefetchTimeout: 1s
  kafka:
    brokers: kafka:9092
    brokerAddressFamily: v4
    socketKeepAliveEnable: true
    topicMetadataRefreshInterval: 10s
  dedupe:
    enabled: false

postgres:
  url: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
  autoMigrate: migration # Runs migrations as part of the service startup, valid values are: ent, migration, false

meters:
  - id: completion_tokens
    slug: completion_tokens
    description: "Track completion tokens from litellm requests"
    eventType: litellm.request
    aggregation: SUM
    valueProperty: $.gen_ai.usage.completion_tokens
    groupBy:
      user_api_key: $.metadata.user_api_key_alias
      requester: $.metadata.requester_metadata
      api_key_metadata: $.metadata.user_api_key_metadata
      api_key_spend: $.metadata.user_api_key_spend
      api_key_max_budget: $.metadata.user_api_key_max_budget
      request_model: $.gen_ai.request.model
      response_model: $.gen_ai.response.model
      system: $.gen_ai.system
      call_type: $.gen_ai.call_type
      prompt_tokens: $.gen_ai.usage.prompt_tokens

portal:
  enabled: true
  tokenSecret: this-isnt-secure