# PostgreSQL configuration
enabled: true

# Set to true to use external managed PostgreSQL
external:
  enabled: false
  url: "postgresql://user:password@host:port/database"

# Self-hosted PostgreSQL configuration (used when external.enabled = false)
internal:
  enabled: true
  password: "postgres"
  storageClass: "standard"
  storageSize: "10Gi"