apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    component: api
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8800
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-secret
                  key: secret-key
            - name: ENABLE_METRICS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: ENABLE_METRICS
            - name: DYNAMODB_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: DYNAMODB_REGION
            - name: SES_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: SES_REGION
            - name: SES_SENDER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: SES_SENDER_EMAIL
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-secret
                  key: stripe-secret-key
            {{- if .Values.webhookSig }}
            - name: WEBHOOK_SIG
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-secret
                  key: webhook-sig
            {{- end }}
            - name: ENABLE_LIMITS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: ENABLE_LIMITS
            - name: ENV_SUFFIX
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: ENV_SUFFIX
            - name: PASSWORDLESS_SIGN_IN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backend.fullname" . }}-config
                  key: PASSWORDLESS_SIGN_IN
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-secret
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.fullname" . }}-secret
                  key: aws-secret-access-key
          livenessProbe:
            httpGet:
              path: /health
              port: 8800
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8800
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory | default "256Mi" }}
              cpu: {{ .Values.resources.requests.cpu | default "250m" }}
            limits:
              memory: {{ .Values.resources.limits.memory | default "512Mi" }}
              cpu: {{ .Values.resources.limits.cpu | default "500m" }}
      restartPolicy: Always