apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.secretKey | b64enc }}
  stripe-secret-key: {{ .Values.stripeSecretKey | b64enc }}
  {{- if .Values.webhookSig }}
  webhook-sig: {{ .Values.webhookSig | b64enc }}
  {{- end }}
  aws-access-key-id: {{ .Values.awsAccessKeyId | b64enc }}
  aws-secret-access-key: {{ .Values.awsSecretAccessKey | b64enc }}