{
 "title": "LLM Overview",
 "tags": [
  "llm",
  "metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment Failures",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(exception_class) (litellm_deployment_failure_responses_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Successes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (litellm_deployment_success_responses_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Failures",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (litellm_llm_api_failed_requests_metric_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "avg by(instance) (irate(litellm_proxy_total_requests_metric_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Models Deployed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count without(litellm_model_name) (sum by(litellm_model_name) (sum_over_time(litellm_deployment_state[1m])))",
     "legendFormat": "Unique Models"
    }
   ]
  },
  {
   "title": "Keys in use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "count without(api_key_alias) (sum by(api_key_alias) (sum_over_time(litellm_input_tokens_created[1m])))",
     "legendFormat": "Unique Keys"
    }
   ]
  },
  {
   "title": "Unique Keys",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "group by(api_key_alias) (litellm_input_tokens_created)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(litellm_llm_api_latency_metric_bucket[1m])))",
     "legendFormat": "p50 {{model}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(litellm_llm_api_latency_metric_bucket[1m])))",
     "legendFormat": "p75 {{model}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(litellm_llm_api_latency_metric_bucket[1m])))",
     "legendFormat": "p99 {{model}}"
    }
   ]
  },
  {
   "title": "LiteLLM Overhead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(litellm_overhead_latency_metric_bucket[1m])))",
     "legendFormat": "p99 {{model}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(litellm_overhead_latency_metric_bucket[1m])))",
     "legendFormat": "p75{{model}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(litellm_overhead_latency_metric_bucket[1m])))",
     "legendFormat": "p50 {{model}}"
    }
   ]
  },
  { "title": "User data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Input Tokens - Rate of change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "avg by(api_key_alias) (rate(litellm_input_tokens_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Tokens - Cumulative Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "avg by(api_key_alias) (litellm_input_tokens_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Tokens - Rate of change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg by(api_key_alias) (rate(litellm_output_tokens_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Tokens - Cumulative Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "avg by(api_key_alias) (litellm_output_tokens_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Model Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Requests - Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(model) (litellm_requests_metric_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - Rate of Change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "max by(model) (rate(litellm_llm_api_latency_metric_sum[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}