apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_API_URL: {{ include "amazee-ai.apiUrl" . }}
  STRIPE_PUBLISHABLE_KEY: "{{ .Values.stripePublishableKey }}"
  PASSWORDLESS_SIGN_IN: "{{ .Values.passwordlessSignIn }}"